name: Mapping BODS lineRef with TfL route numbers

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mapping BODS lineRef with TfL route numbers
        env:
          TFL_API_KEY: ${{ secrets.TFL_API_KEY }}
        run: |
          python -u bods.py

      - name: Set commit message with timestamp
        run: echo "COMMIT_MSG=Mapping BODS lineRef with TfL route numbers at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            target-folder: data/
            folder: data
            commit-message: ${{ env.COMMIT_MSG }}
            branch: gh-pages
            clean: false