name: Clear gh-pages Branch

on:
  workflow_dispatch:

jobs:
  clear-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Remove all files
        run: |
          git rm -rf .
          # rm -rf ./* .[^.]* || true  # Remove everything including hidden files
          
          touch README.md
          git add README.md

          git config --global user.name "Xavier Fung"
          git config --global user.email "1157303+xavier114fch@users.noreply.github.com"
          git commit -m "Clear gh-pages branch [skip ci]" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push origin gh-pages --force