name: Naptan Download and Parse Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Naptan
        run: |
          python naptan.py
          find data/naptan -maxdepth 1 -type f -regex './naptan_[0-9]\+\.json' -delete
          find data/naptan -maxdepth 1 -type f -regex './naptan_[0-9]\+\.xml' -delete

      - name: Deploy to gh-pages under /data/naptan
        run: |
          git config --global user.name "Xavier Fung"
          git config --global user.email "1157303+xavier114fch@users.noreply.github.com"

          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp -r data/naptan gh-pages/data/

          cd gh-pages
          git add data/naptan
          git commit -m "Update Naptan data" || echo "No changes to commit"
          git push origin gh-pages