name: NOC Download and Parse Data

on:
  schedule:
    - cron: '0 7,19 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch NOC
        run: |
          python -u noc.py

      - name: Set commit message with timestamp
        run: echo "COMMIT_MSG=Update NOC at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            target-folder: data/
            folder: data
            commit-message: ${{ env.COMMIT_MSG }}
            branch: gh-pages
            clean: false