name: NPTG Download and Parse Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch NPTG
        run: |
          python nptg.py
          rm -f data/nptg/nptg.xml data/nptg/nptg.json

      - name: Deploy to gh-pages under /data/nptg
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            target-folder: data/
            folder: data
            commit-message: "Update resources from ${{ github.run_number }}:${{ github.run_attempt }}"
            branch: gh-pages
            clean: false
